apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-yaml
  name: nginx-yaml
spec:
  containers:
  - image: httpd
    name: nginx-yaml
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
